name: Test

on:
  push:
  pull_request:

env:
  FORCE_COLOR: 2

jobs:
  full:
    name: Full in Node.js 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 15
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run all tests
        run: yarn test

  short:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 10
          - 12
          - 14
    name: Quick in Node.js ${{ matrix.node-version }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run code tests
        run: npx jest
